on: 
  push:
    branches:
      - main
      - "release /**"

    path:
      - "src/**"  

  pull_request:
    branches:
      - main
      - "release /**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6-beta

      - name: Run Tests
        run: npm test
